### ISSUE TITLE
Bug in rainbow.yml 

### ISSUE THREAD

**Issue by zionrubin** [Natural-Intelligence/liminal#44]
```
    - task: my_parallelized_static_input_task
        type: python
        description: parallelized static input task
        image: my_static_input_task_image
        env_vars:
          env1: "a"
          env2: "b"
        input_type: static
        input_path: '[ { "foo": "bar" }, { "foo": "baz" } ]'
        split_input: True
        executors: 2
        cmd: python -u **helloworld.py**
```
it should be hello_world.py
